### ISSUE TITLE
Upgrade to 0.4.0

### ISSUE THREAD

**Issue by AndrewKeig** [s9tpepper/grunt-cucumber-js#19]
Hi 

I appreciate you are busy but would it possible to upgrade cucumber to 0.4.0 this now has support for tables; I will give you a couple of days. If no change I will assume you are no longer interested in this and fork and publish to npm.  If you would like to hand this off, I will gladly take it on.

Thanks

**Comment by Phoscur** [comment]
@AndrewKeig hey, so could you take the other pull requests into your repo too, like the coffee option?

**Comment by AndrewKeig** [comment]
Im up against it this week, but more than happy to add you to the repo, if you have time.

**Comment by Phoscur** [comment]
well I just want an up to date npm package, if you need me to contribute for that, let it be so :)
@AndrewKeig
